### ISSUE TITLE
Device Mismatch.

### ISSUE THREAD

**Issue by abhimanyuchadha96** [scabini/RADAM#1]
https://github.com/scabini/RADAM/blob/61f33cd138788ddbe018971fca00ef6b4cfd1765/standalone_RADAM_example.py#L25

https://github.com/scabini/RADAM/blob/61f33cd138788ddbe018971fca00ef6b4cfd1765/standalone_RADAM_example.py#L137

The example input tensors should also have a `to.(device)` so that they end up on the GPU when available.

**Comment by scabini** [comment]
This is fixed now, thank you very much for pointing it out. I made the mistake of testing this script only on my machine without a GPU.

**Comment by scabini** [comment]
This is fixed now, thank you very much for pointing it out. I made the mistake of testing this script only on my machine without a GPU.
